setup:
  channels: &setup_channels
    - conda-forge
    - defaults
  dependencies: &setup_dependencies
    - python
    - setuptools
    - numpy

production:
  channels: &production_channels
    - defaults
  dependencies: &production_dependencies
    - python

development: # inherits production
  channels:
    - *setup_channels
    - *production_channels
  dependencies:
    - *setup_dependencies
    - *production_dependencies
    - pyyaml

test: # inherits production
  channels:
    - *setup_channels
    - *production_channels
  dependencies:
    - *setup_dependencies
    - *production_dependencies
    - pytest
    - pip
    - pytest-cov
    - codecov

docs: # inherits production
  channels:
    - *setup_channels
    - *production_channels
  dependencies:
    - *setup_dependencies
    - *production_dependencies
    - jupyterlab
    - sphinx
    - sphinx_rtd_theme
    - sphinxcontrib-bibtex
    - nbsphinx
    - recommonmark
    - sphinx-markdown-tables

conda-build:
  channels:
    - *setup_channels
  dependencies:
    - *setup_dependencies
    - anaconda-client
    - conda-build

