production:
  channels: &production_channels
    - defaults
  dependencies: &production_dependencies
    - python

development: # inherits production
  channels:
    - *production_channels
  dependencies:
    - *production_dependencies
    - pyyaml

test: # inherits production
  channels:
    - *production_channels
  dependencies:
    - *production_dependencies
    - pytest
    - pip
    - pytest-cov
    - codecov

docs: # inherits production
  channels:
    - *production_channels
  dependencies:
    - *production_dependencies
    - jupyterlab
    - sphinx
    - sphinx_rtd_theme
    - sphinxcontrib-bibtex
    - nbsphinx
    - recommonmark
    - sphinx-markdown-tables

setup:
  channels:
    - defaults
  dependencies:
    - python
    - setuptools
    - numpy
    - versioneer

conda-build:
  channels:
    - defaults
  dependencies:
    - python
    - anaconda-client
    - conda-build

