package:
  name: evidence
  version: "{{ environ['GIT_DESCRIBE_TAG'] }}"

source:
  path: ../../

build:
  number: 1

requirements:
  build:
    - python
    - setuptools
    - numpy

  run:
    - python

about:
  home: https://uibcdf.org
  license: MIT License
  summary: ""
  description: |
    This library provides...
  dev_url: https://github.com/uibcdf/evidence
  doc_url: https://uibcdf.org/evidence

