package:
  name: evidence
  version: "{{ environ['GIT_DESCRIBE_TAG'] }}"
source:
  path: ../../
build:
  number: 1
requirements:
  build:
  - python
  - pip
  - setuptools >=61.0
  - versioningit ~=2.0
  run:
  - python
  - pip
  - setuptools >=61.0
  - versioningit ~=2.0
about:
  description: This library provides...
  dev_url: https://github.com/uibcdf/Evidence
  doc_url: https://uibcdf.org/Evidence
  home: https://uibcdf.org
  license: MIT License
  summary: ''
