about:
  description: This library provides...
  dev_url: https://github.com/uibcdf/evidence
  doc_url: https://uibcdf.org/evidence
  home: https://uibcdf.org
  license: MIT License
  summary: ''
build:
  number: 1
package:
  name: evidence
  version: '{{ environ["GIT_DESCRIBE_TAG"] }}'
requirements:
  build:
  - python
  - setuptools
  - numpy
  run:
  - python
source:
  path: ../../
